#!/bin/bash

for f in bashrc inputrc vimrc tmux.conf ; do
    dest=~/.$f
    link=$(realpath $dest)

    if [[ $dest = $f ]] ; then
        echo "$dest was installed already"
        continue
    fi

    if [[ -e $dest ]] ; then
        echo "Creating backup for $dest"
        mv $dest{,.bak}
    fi

    echo "Installing $dest"
    ln -s $(pwd)/$f $dest
done

curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
